services:
  - type: web
    name: amantena-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: cd backend && npm install && npx prisma generate
    startCommand: cd backend && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: amantena-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: CLOUDINARY_CLOUD_NAME
        value: dnerhroxc
      - key: CLOUDINARY_API_KEY
        value: "668351163117448"
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://amantena.netlify.app
      - key: PORT
        value: 5000

databases:
  - name: amantena-db
    databaseName: amantena
    user: postgres
